// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_tx_qpsk_Block_entry11_proc26 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input2_val,
        temp1_re_din,
        temp1_re_full_n,
        temp1_re_write,
        input1_val,
        temp1_im_din,
        temp1_im_full_n,
        temp1_im_write
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] input2_val;
output  [15:0] temp1_re_din;
input   temp1_re_full_n;
output   temp1_re_write;
input  [0:0] input1_val;
output  [15:0] temp1_im_din;
input   temp1_im_full_n;
output   temp1_im_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg temp1_re_write;
reg temp1_im_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] mapping_address0;
reg    mapping_ce0;
wire   [1:0] mapping_q0;
wire   [0:0] mapping_address1;
reg    mapping_ce1;
wire   [1:0] mapping_q1;
reg    temp1_re_blk_n;
wire    ap_CS_fsm_state17;
reg    temp1_im_blk_n;
reg    ap_block_state1;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_127_p1;
reg   [63:0] conv_reg_661;
wire    ap_CS_fsm_state3;
wire   [63:0] grp_fu_130_p1;
reg   [63:0] conv5_reg_666;
wire   [63:0] grp_fu_117_p2;
reg   [63:0] pf_reg_671;
wire    ap_CS_fsm_state16;
wire   [63:0] grp_fu_122_p2;
reg   [63:0] pf_1_reg_676;
wire   [63:0] zext_ln18_fu_133_p1;
wire   [63:0] zext_ln19_fu_138_p1;
reg    ap_block_state17;
wire    ap_CS_fsm_state4;
wire  signed [31:0] grp_fu_127_p0;
wire  signed [31:0] grp_fu_130_p0;
wire   [63:0] bitcast_ln724_fu_153_p1;
wire   [10:0] tmp4_fu_168_p4;
wire   [51:0] trunc_ln18_1_fu_182_p1;
wire   [52:0] zext_ln18_2_cast_fu_186_p3;
wire   [53:0] zext_ln18_2_fu_194_p1;
wire   [0:0] tmp_fu_160_p3;
wire   [53:0] sub_ln18_fu_198_p2;
wire   [62:0] trunc_ln18_fu_156_p1;
wire   [11:0] zext_ln18_1_fu_178_p1;
wire   [11:0] sub_ln18_1_fu_218_p2;
wire   [0:0] icmp_ln18_1_fu_224_p2;
wire   [11:0] add_ln18_fu_230_p2;
wire   [11:0] sub_ln18_2_fu_236_p2;
wire  signed [11:0] select_ln18_1_fu_242_p3;
wire   [53:0] select_ln18_fu_204_p3;
wire  signed [31:0] sext_ln18_fu_250_p1;
wire   [53:0] zext_ln18_3_fu_270_p1;
wire   [53:0] ashr_ln18_fu_274_p2;
wire   [0:0] tmp_5_fu_284_p3;
wire   [0:0] icmp_ln18_3_fu_264_p2;
wire   [15:0] trunc_ln18_3_fu_280_p1;
wire   [15:0] select_ln18_6_fu_292_p3;
wire   [7:0] tmp_6_fu_308_p4;
wire   [15:0] trunc_ln18_2_fu_260_p1;
wire   [15:0] sext_ln18cast_fu_324_p1;
wire   [0:0] icmp_ln18_4_fu_318_p2;
wire   [15:0] shl_ln18_fu_328_p2;
wire   [0:0] icmp_ln18_fu_212_p2;
wire   [15:0] select_ln18_3_fu_334_p3;
wire   [0:0] icmp_ln18_2_fu_254_p2;
wire   [0:0] xor_ln18_fu_350_p2;
wire   [0:0] and_ln18_fu_356_p2;
wire   [15:0] select_ln18_4_fu_342_p3;
wire   [0:0] or_ln18_fu_370_p2;
wire   [0:0] xor_ln18_1_fu_376_p2;
wire   [0:0] and_ln18_1_fu_382_p2;
wire   [15:0] select_ln18_2_fu_300_p3;
wire   [15:0] select_ln18_5_fu_362_p3;
wire   [63:0] bitcast_ln724_1_fu_397_p1;
wire   [10:0] tmp_s_fu_412_p4;
wire   [51:0] trunc_ln19_1_fu_426_p1;
wire   [52:0] zext_ln19_2_cast_fu_430_p3;
wire   [53:0] zext_ln19_2_fu_438_p1;
wire   [0:0] tmp_7_fu_404_p3;
wire   [53:0] sub_ln19_fu_442_p2;
wire   [62:0] trunc_ln19_fu_400_p1;
wire   [11:0] zext_ln19_1_fu_422_p1;
wire   [11:0] sub_ln19_1_fu_462_p2;
wire   [0:0] icmp_ln19_1_fu_468_p2;
wire   [11:0] add_ln19_fu_474_p2;
wire   [11:0] sub_ln19_2_fu_480_p2;
wire  signed [11:0] select_ln19_1_fu_486_p3;
wire   [53:0] select_ln19_fu_448_p3;
wire  signed [31:0] sext_ln19_fu_494_p1;
wire   [53:0] zext_ln19_3_fu_514_p1;
wire   [53:0] ashr_ln19_fu_518_p2;
wire   [0:0] tmp_8_fu_528_p3;
wire   [0:0] icmp_ln19_3_fu_508_p2;
wire   [15:0] trunc_ln19_3_fu_524_p1;
wire   [15:0] select_ln19_6_fu_536_p3;
wire   [7:0] tmp_9_fu_552_p4;
wire   [15:0] trunc_ln19_2_fu_504_p1;
wire   [15:0] sext_ln19cast_fu_568_p1;
wire   [0:0] icmp_ln19_4_fu_562_p2;
wire   [15:0] shl_ln19_fu_572_p2;
wire   [0:0] icmp_ln19_fu_456_p2;
wire   [15:0] select_ln19_3_fu_578_p3;
wire   [0:0] icmp_ln19_2_fu_498_p2;
wire   [0:0] xor_ln19_fu_594_p2;
wire   [0:0] and_ln19_fu_600_p2;
wire   [15:0] select_ln19_4_fu_586_p3;
wire   [0:0] or_ln19_fu_614_p2;
wire   [0:0] xor_ln19_1_fu_620_p2;
wire   [0:0] and_ln19_1_fu_626_p2;
wire   [15:0] select_ln19_2_fu_544_p3;
wire   [15:0] select_ln19_5_fu_606_p3;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 17'd1;
end

top_tx_qpsk_Block_entry11_proc26_mapping_ROM_AUTO_1R #(
    .DataWidth( 2 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
mapping_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mapping_address0),
    .ce0(mapping_ce0),
    .q0(mapping_q0),
    .address1(mapping_address1),
    .ce1(mapping_ce1),
    .q1(mapping_q1)
);

top_tx_ddiv_64ns_64ns_64_13_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_13_no_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_reg_661),
    .din1(64'd4609047870845172685),
    .ce(1'b1),
    .dout(grp_fu_117_p2)
);

top_tx_ddiv_64ns_64ns_64_13_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_13_no_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv5_reg_666),
    .din1(64'd4609047870845172685),
    .ce(1'b1),
    .dout(grp_fu_122_p2)
);

top_tx_sitodp_32s_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_2_no_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_127_p0),
    .ce(1'b1),
    .dout(grp_fu_127_p1)
);

top_tx_sitodp_32s_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_2_no_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_130_p0),
    .ce(1'b1),
    .dout(grp_fu_130_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        conv5_reg_666 <= grp_fu_130_p1;
        conv_reg_661 <= grp_fu_127_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        pf_1_reg_676 <= grp_fu_122_p2;
        pf_reg_671 <= grp_fu_117_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if (((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0))) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mapping_ce0 = 1'b1;
    end else begin
        mapping_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mapping_ce1 = 1'b1;
    end else begin
        mapping_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp1_im_blk_n = temp1_im_full_n;
    end else begin
        temp1_im_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        temp1_im_write = 1'b1;
    end else begin
        temp1_im_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp1_re_blk_n = temp1_re_full_n;
    end else begin
        temp1_re_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        temp1_re_write = 1'b1;
    end else begin
        temp1_re_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if ((~((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_fu_230_p2 = ($signed(sub_ln18_1_fu_218_p2) + $signed(12'd4082));

assign add_ln19_fu_474_p2 = ($signed(sub_ln19_1_fu_462_p2) + $signed(12'd4082));

assign and_ln18_1_fu_382_p2 = (xor_ln18_1_fu_376_p2 & icmp_ln18_1_fu_224_p2);

assign and_ln18_fu_356_p2 = (xor_ln18_fu_350_p2 & icmp_ln18_2_fu_254_p2);

assign and_ln19_1_fu_626_p2 = (xor_ln19_1_fu_620_p2 & icmp_ln19_1_fu_468_p2);

assign and_ln19_fu_600_p2 = (xor_ln19_fu_594_p2 & icmp_ln19_2_fu_498_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state17 = ((temp1_im_full_n == 1'b0) | (temp1_re_full_n == 1'b0));
end

assign ashr_ln18_fu_274_p2 = $signed(select_ln18_fu_204_p3) >>> zext_ln18_3_fu_270_p1;

assign ashr_ln19_fu_518_p2 = $signed(select_ln19_fu_448_p3) >>> zext_ln19_3_fu_514_p1;

assign bitcast_ln724_1_fu_397_p1 = pf_1_reg_676;

assign bitcast_ln724_fu_153_p1 = pf_reg_671;

assign grp_fu_127_p0 = $signed(mapping_q1);

assign grp_fu_130_p0 = $signed(mapping_q0);

assign icmp_ln18_1_fu_224_p2 = (($signed(sub_ln18_1_fu_218_p2) > $signed(12'd14)) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_254_p2 = ((sub_ln18_1_fu_218_p2 == 12'd14) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_264_p2 = ((select_ln18_1_fu_242_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln18_4_fu_318_p2 = ((tmp_6_fu_308_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_212_p2 = ((trunc_ln18_fu_156_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_1_fu_468_p2 = (($signed(sub_ln19_1_fu_462_p2) > $signed(12'd14)) ? 1'b1 : 1'b0);

assign icmp_ln19_2_fu_498_p2 = ((sub_ln19_1_fu_462_p2 == 12'd14) ? 1'b1 : 1'b0);

assign icmp_ln19_3_fu_508_p2 = ((select_ln19_1_fu_486_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln19_4_fu_562_p2 = ((tmp_9_fu_552_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_456_p2 = ((trunc_ln19_fu_400_p1 == 63'd0) ? 1'b1 : 1'b0);

assign mapping_address0 = zext_ln19_fu_138_p1;

assign mapping_address1 = zext_ln18_fu_133_p1;

assign or_ln18_fu_370_p2 = (icmp_ln18_fu_212_p2 | icmp_ln18_2_fu_254_p2);

assign or_ln19_fu_614_p2 = (icmp_ln19_fu_456_p2 | icmp_ln19_2_fu_498_p2);

assign select_ln18_1_fu_242_p3 = ((icmp_ln18_1_fu_224_p2[0:0] == 1'b1) ? add_ln18_fu_230_p2 : sub_ln18_2_fu_236_p2);

assign select_ln18_2_fu_300_p3 = ((icmp_ln18_3_fu_264_p2[0:0] == 1'b1) ? trunc_ln18_3_fu_280_p1 : select_ln18_6_fu_292_p3);

assign select_ln18_3_fu_334_p3 = ((icmp_ln18_4_fu_318_p2[0:0] == 1'b1) ? shl_ln18_fu_328_p2 : 16'd0);

assign select_ln18_4_fu_342_p3 = ((icmp_ln18_fu_212_p2[0:0] == 1'b1) ? 16'd0 : select_ln18_3_fu_334_p3);

assign select_ln18_5_fu_362_p3 = ((and_ln18_fu_356_p2[0:0] == 1'b1) ? trunc_ln18_2_fu_260_p1 : select_ln18_4_fu_342_p3);

assign select_ln18_6_fu_292_p3 = ((tmp_5_fu_284_p3[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln18_fu_204_p3 = ((tmp_fu_160_p3[0:0] == 1'b1) ? sub_ln18_fu_198_p2 : zext_ln18_2_fu_194_p1);

assign select_ln19_1_fu_486_p3 = ((icmp_ln19_1_fu_468_p2[0:0] == 1'b1) ? add_ln19_fu_474_p2 : sub_ln19_2_fu_480_p2);

assign select_ln19_2_fu_544_p3 = ((icmp_ln19_3_fu_508_p2[0:0] == 1'b1) ? trunc_ln19_3_fu_524_p1 : select_ln19_6_fu_536_p3);

assign select_ln19_3_fu_578_p3 = ((icmp_ln19_4_fu_562_p2[0:0] == 1'b1) ? shl_ln19_fu_572_p2 : 16'd0);

assign select_ln19_4_fu_586_p3 = ((icmp_ln19_fu_456_p2[0:0] == 1'b1) ? 16'd0 : select_ln19_3_fu_578_p3);

assign select_ln19_5_fu_606_p3 = ((and_ln19_fu_600_p2[0:0] == 1'b1) ? trunc_ln19_2_fu_504_p1 : select_ln19_4_fu_586_p3);

assign select_ln19_6_fu_536_p3 = ((tmp_8_fu_528_p3[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln19_fu_448_p3 = ((tmp_7_fu_404_p3[0:0] == 1'b1) ? sub_ln19_fu_442_p2 : zext_ln19_2_fu_438_p1);

assign sext_ln18_fu_250_p1 = select_ln18_1_fu_242_p3;

assign sext_ln18cast_fu_324_p1 = sext_ln18_fu_250_p1[15:0];

assign sext_ln19_fu_494_p1 = select_ln19_1_fu_486_p3;

assign sext_ln19cast_fu_568_p1 = sext_ln19_fu_494_p1[15:0];

assign shl_ln18_fu_328_p2 = trunc_ln18_2_fu_260_p1 << sext_ln18cast_fu_324_p1;

assign shl_ln19_fu_572_p2 = trunc_ln19_2_fu_504_p1 << sext_ln19cast_fu_568_p1;

assign sub_ln18_1_fu_218_p2 = (12'd1075 - zext_ln18_1_fu_178_p1);

assign sub_ln18_2_fu_236_p2 = (12'd14 - sub_ln18_1_fu_218_p2);

assign sub_ln18_fu_198_p2 = (54'd0 - zext_ln18_2_fu_194_p1);

assign sub_ln19_1_fu_462_p2 = (12'd1075 - zext_ln19_1_fu_422_p1);

assign sub_ln19_2_fu_480_p2 = (12'd14 - sub_ln19_1_fu_462_p2);

assign sub_ln19_fu_442_p2 = (54'd0 - zext_ln19_2_fu_438_p1);

assign temp1_im_din = ((and_ln19_1_fu_626_p2[0:0] == 1'b1) ? select_ln19_2_fu_544_p3 : select_ln19_5_fu_606_p3);

assign temp1_re_din = ((and_ln18_1_fu_382_p2[0:0] == 1'b1) ? select_ln18_2_fu_300_p3 : select_ln18_5_fu_362_p3);

assign tmp4_fu_168_p4 = {{bitcast_ln724_fu_153_p1[62:52]}};

assign tmp_5_fu_284_p3 = bitcast_ln724_fu_153_p1[32'd63];

assign tmp_6_fu_308_p4 = {{select_ln18_1_fu_242_p3[11:4]}};

assign tmp_7_fu_404_p3 = bitcast_ln724_1_fu_397_p1[32'd63];

assign tmp_8_fu_528_p3 = bitcast_ln724_1_fu_397_p1[32'd63];

assign tmp_9_fu_552_p4 = {{select_ln19_1_fu_486_p3[11:4]}};

assign tmp_fu_160_p3 = bitcast_ln724_fu_153_p1[32'd63];

assign tmp_s_fu_412_p4 = {{bitcast_ln724_1_fu_397_p1[62:52]}};

assign trunc_ln18_1_fu_182_p1 = bitcast_ln724_fu_153_p1[51:0];

assign trunc_ln18_2_fu_260_p1 = select_ln18_fu_204_p3[15:0];

assign trunc_ln18_3_fu_280_p1 = ashr_ln18_fu_274_p2[15:0];

assign trunc_ln18_fu_156_p1 = bitcast_ln724_fu_153_p1[62:0];

assign trunc_ln19_1_fu_426_p1 = bitcast_ln724_1_fu_397_p1[51:0];

assign trunc_ln19_2_fu_504_p1 = select_ln19_fu_448_p3[15:0];

assign trunc_ln19_3_fu_524_p1 = ashr_ln19_fu_518_p2[15:0];

assign trunc_ln19_fu_400_p1 = bitcast_ln724_1_fu_397_p1[62:0];

assign xor_ln18_1_fu_376_p2 = (or_ln18_fu_370_p2 ^ 1'd1);

assign xor_ln18_fu_350_p2 = (icmp_ln18_fu_212_p2 ^ 1'd1);

assign xor_ln19_1_fu_620_p2 = (or_ln19_fu_614_p2 ^ 1'd1);

assign xor_ln19_fu_594_p2 = (icmp_ln19_fu_456_p2 ^ 1'd1);

assign zext_ln18_1_fu_178_p1 = tmp4_fu_168_p4;

assign zext_ln18_2_cast_fu_186_p3 = {{1'd1}, {trunc_ln18_1_fu_182_p1}};

assign zext_ln18_2_fu_194_p1 = zext_ln18_2_cast_fu_186_p3;

assign zext_ln18_3_fu_270_p1 = $unsigned(sext_ln18_fu_250_p1);

assign zext_ln18_fu_133_p1 = input2_val;

assign zext_ln19_1_fu_422_p1 = tmp_s_fu_412_p4;

assign zext_ln19_2_cast_fu_430_p3 = {{1'd1}, {trunc_ln19_1_fu_426_p1}};

assign zext_ln19_2_fu_438_p1 = zext_ln19_2_cast_fu_430_p3;

assign zext_ln19_3_fu_514_p1 = $unsigned(sext_ln19_fu_494_p1);

assign zext_ln19_fu_138_p1 = input1_val;

endmodule //top_tx_qpsk_Block_entry11_proc26
