// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_tx_top_tx,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=155158,HLS_SYN_TPT=none,HLS_SYN_MEM=103,HLS_SYN_DSP=0,HLS_SYN_FF=12226,HLS_SYN_LUT=19117,HLS_VERSION=2023_1}" *)

module top_tx (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        en_qpsk,
        en_qam16,
        en_qam64,
        user_id0,
        user_id1,
        input1_TDATA,
        input1_TVALID,
        input1_TREADY,
        input2_TDATA,
        input2_TVALID,
        input2_TREADY,
        input3_TDATA,
        input3_TVALID,
        input3_TREADY,
        input4_TDATA,
        input4_TVALID,
        input4_TREADY,
        input5_TDATA,
        input5_TVALID,
        input5_TREADY,
        input6_TDATA,
        input6_TVALID,
        input6_TREADY,
        cp_outre_TDATA,
        cp_outre_TVALID,
        cp_outre_TREADY,
        cp_outre_TKEEP,
        cp_outre_TSTRB,
        cp_outre_TLAST,
        cp_outim_TDATA,
        cp_outim_TVALID,
        cp_outim_TREADY,
        cp_outim_TKEEP,
        cp_outim_TSTRB,
        cp_outim_TLAST
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] en_qpsk;
input  [0:0] en_qam16;
input  [0:0] en_qam64;
input  [0:0] user_id0;
input  [0:0] user_id1;
input  [7:0] input1_TDATA;
input   input1_TVALID;
output   input1_TREADY;
input  [7:0] input2_TDATA;
input   input2_TVALID;
output   input2_TREADY;
input  [7:0] input3_TDATA;
input   input3_TVALID;
output   input3_TREADY;
input  [7:0] input4_TDATA;
input   input4_TVALID;
output   input4_TREADY;
input  [7:0] input5_TDATA;
input   input5_TVALID;
output   input5_TREADY;
input  [7:0] input6_TDATA;
input   input6_TVALID;
output   input6_TREADY;
output  [15:0] cp_outre_TDATA;
output   cp_outre_TVALID;
input   cp_outre_TREADY;
output  [1:0] cp_outre_TKEEP;
output  [1:0] cp_outre_TSTRB;
output  [0:0] cp_outre_TLAST;
output  [15:0] cp_outim_TDATA;
output   cp_outim_TVALID;
input   cp_outim_TREADY;
output  [1:0] cp_outim_TKEEP;
output  [1:0] cp_outim_TSTRB;
output  [0:0] cp_outim_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
reg   [2:0] block_1_reg_501;
wire    ap_CS_fsm_state8;
wire   [12:0] tmp_3_fu_392_p3;
reg   [12:0] tmp_3_reg_509;
wire   [0:0] icmp_ln109_fu_380_p2;
reg   [12:0] temp2_re_address0;
reg    temp2_re_ce0;
reg    temp2_re_we0;
wire   [15:0] temp2_re_q0;
reg   [12:0] temp2_im_address0;
reg    temp2_im_ce0;
reg    temp2_im_we0;
wire   [15:0] temp2_im_q0;
reg   [12:0] temp_out_M_real_address0;
reg    temp_out_M_real_ce0;
reg    temp_out_M_real_we0;
reg   [15:0] temp_out_M_real_d0;
wire   [15:0] temp_out_M_real_q0;
reg   [12:0] temp_out_M_imag_address0;
reg    temp_out_M_imag_ce0;
reg    temp_out_M_imag_we0;
reg   [15:0] temp_out_M_imag_d0;
wire   [15:0] temp_out_M_imag_q0;
reg   [12:0] temp_out1_M_real_address0;
reg    temp_out1_M_real_ce0;
reg    temp_out1_M_real_we0;
wire   [15:0] temp_out1_M_real_q0;
reg   [12:0] temp_out1_M_imag_address0;
reg    temp_out1_M_imag_ce0;
reg    temp_out1_M_imag_we0;
wire   [15:0] temp_out1_M_imag_q0;
wire    grp_mods_fu_261_ap_start;
wire    grp_mods_fu_261_ap_done;
wire    grp_mods_fu_261_ap_idle;
wire    grp_mods_fu_261_ap_ready;
wire    grp_mods_fu_261_input1_TREADY;
wire    grp_mods_fu_261_input2_TREADY;
wire    grp_mods_fu_261_input3_TREADY;
wire    grp_mods_fu_261_input4_TREADY;
wire    grp_mods_fu_261_input5_TREADY;
wire    grp_mods_fu_261_input6_TREADY;
wire   [15:0] grp_mods_fu_261_temp1_re_din;
wire    grp_mods_fu_261_temp1_re_write;
wire   [15:0] grp_mods_fu_261_temp1_im_din;
wire    grp_mods_fu_261_temp1_im_write;
wire    grp_adding_pilot_fu_293_ap_start;
wire    grp_adding_pilot_fu_293_ap_done;
wire    grp_adding_pilot_fu_293_ap_idle;
wire    grp_adding_pilot_fu_293_ap_ready;
wire    grp_adding_pilot_fu_293_temp1_re_read;
wire    grp_adding_pilot_fu_293_temp1_im_read;
wire   [12:0] grp_adding_pilot_fu_293_out_re_arr_address0;
wire    grp_adding_pilot_fu_293_out_re_arr_ce0;
wire    grp_adding_pilot_fu_293_out_re_arr_we0;
wire   [15:0] grp_adding_pilot_fu_293_out_re_arr_d0;
wire   [12:0] grp_adding_pilot_fu_293_out_im_arr_address0;
wire    grp_adding_pilot_fu_293_out_im_arr_ce0;
wire    grp_adding_pilot_fu_293_out_im_arr_we0;
wire   [15:0] grp_adding_pilot_fu_293_out_im_arr_d0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_ap_start;
wire    grp_top_tx_Pipeline_input_loop_fu_309_ap_done;
wire    grp_top_tx_Pipeline_input_loop_fu_309_ap_idle;
wire    grp_top_tx_Pipeline_input_loop_fu_309_ap_ready;
wire   [12:0] grp_top_tx_Pipeline_input_loop_fu_309_temp2_re_address0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_temp2_re_ce0;
wire   [12:0] grp_top_tx_Pipeline_input_loop_fu_309_temp2_im_address0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_temp2_im_ce0;
wire   [12:0] grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_address0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_ce0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_we0;
wire   [15:0] grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_d0;
wire   [12:0] grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_address0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_ce0;
wire    grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_we0;
wire   [15:0] grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_d0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_done;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_idle;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_ready;
wire   [31:0] grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_xn_i_din;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_xn_i_write;
wire   [12:0] grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_real_address0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_real_ce0;
wire   [12:0] grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_imag_address0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_imag_ce0;
wire    grp_top_tx_Pipeline_loop_output_fu_325_ap_start;
wire    grp_top_tx_Pipeline_loop_output_fu_325_ap_done;
wire    grp_top_tx_Pipeline_loop_output_fu_325_ap_idle;
wire    grp_top_tx_Pipeline_loop_output_fu_325_ap_ready;
wire    grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TREADY;
wire    grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TREADY;
wire   [12:0] grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_real_address0;
wire    grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_real_ce0;
wire   [12:0] grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_imag_address0;
wire    grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_imag_ce0;
wire   [15:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TDATA;
wire    grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID;
wire   [1:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TKEEP;
wire   [1:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TSTRB;
wire   [0:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TLAST;
wire   [15:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TDATA;
wire    grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID;
wire   [1:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TKEEP;
wire   [1:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TSTRB;
wire   [0:0] grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TLAST;
reg    grp_fft_syn_config1_s_fu_347_ap_ce;
wire    grp_fft_syn_config1_s_fu_347_ap_start;
wire    grp_fft_syn_config1_s_fu_347_ap_done;
wire    grp_fft_syn_config1_s_fu_347_ap_idle;
wire    grp_fft_syn_config1_s_fu_347_ap_ready;
wire    grp_fft_syn_config1_s_fu_347_xn_read;
wire   [31:0] grp_fft_syn_config1_s_fu_347_xk_din;
wire    grp_fft_syn_config1_s_fu_347_xk_write;
wire   [7:0] grp_fft_syn_config1_s_fu_347_status_data_V_din;
wire    grp_fft_syn_config1_s_fu_347_status_data_V_write;
wire    grp_fft_syn_config1_s_fu_347_config_ch_data_V_read;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_done;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_idle;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_ready;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_xk_i_read;
wire   [12:0] grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_address0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_ce0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_we0;
wire   [15:0] grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_d0;
wire   [12:0] grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_address0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_ce0;
wire    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_we0;
wire   [15:0] grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_d0;
wire    grp_cp_fu_363_ap_start;
wire    grp_cp_fu_363_ap_done;
wire    grp_cp_fu_363_ap_idle;
wire    grp_cp_fu_363_ap_ready;
wire   [12:0] grp_cp_fu_363_nocp_M_real_address0;
wire    grp_cp_fu_363_nocp_M_real_ce0;
wire   [12:0] grp_cp_fu_363_nocp_M_imag_address0;
wire    grp_cp_fu_363_nocp_M_imag_ce0;
wire   [12:0] grp_cp_fu_363_cp_out_M_real_address0;
wire    grp_cp_fu_363_cp_out_M_real_ce0;
wire    grp_cp_fu_363_cp_out_M_real_we0;
wire   [15:0] grp_cp_fu_363_cp_out_M_real_d0;
wire   [12:0] grp_cp_fu_363_cp_out_M_imag_address0;
wire    grp_cp_fu_363_cp_out_M_imag_ce0;
wire    grp_cp_fu_363_cp_out_M_imag_we0;
wire   [15:0] grp_cp_fu_363_cp_out_M_imag_d0;
reg    grp_mods_fu_261_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    temp1_re_full_n;
reg    temp1_re_write;
wire    temp1_im_full_n;
reg    temp1_im_write;
reg    grp_adding_pilot_fu_293_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [15:0] temp1_re_dout;
wire    temp1_re_empty_n;
reg    temp1_re_read;
wire   [15:0] temp1_im_dout;
wire    temp1_im_empty_n;
reg    temp1_im_read;
reg    grp_top_tx_Pipeline_input_loop_fu_309_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    xn_i_full_n;
reg    xn_i_write;
reg    grp_top_tx_Pipeline_loop_output_fu_325_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_fft_syn_config1_s_fu_347_ap_start_reg;
wire   [31:0] xn_i_dout;
wire    xn_i_empty_n;
reg    xn_i_read;
wire    xk_i_full_n;
reg    xk_i_write;
wire    status_s_full_n;
reg    status_s_write;
wire   [15:0] config_s_dout;
wire    config_s_empty_n;
reg    config_s_read;
reg    grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire   [31:0] xk_i_dout;
wire    xk_i_empty_n;
reg    xk_i_read;
reg    grp_cp_fu_363_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg   [15:0] fft_config_fu_164;
wire   [15:0] fft_config_1_fu_409_p5;
wire    ap_CS_fsm_state10;
wire   [15:0] config_s_din;
wire    config_s_full_n;
reg    config_s_write;
reg   [2:0] block_fu_168;
wire   [2:0] add_ln109_fu_386_p2;
wire   [7:0] status_s_dout;
wire    status_s_empty_n;
reg    status_s_read;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state19;
wire    regslice_both_cp_outre_V_data_V_U_apdone_blk;
wire    regslice_both_cp_outim_V_data_V_U_apdone_blk;
reg    ap_block_state19;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    regslice_both_input1_U_apdone_blk;
wire   [7:0] input1_TDATA_int_regslice;
wire    input1_TVALID_int_regslice;
reg    input1_TREADY_int_regslice;
wire    regslice_both_input1_U_ack_in;
wire    regslice_both_input2_U_apdone_blk;
wire   [7:0] input2_TDATA_int_regslice;
wire    input2_TVALID_int_regslice;
reg    input2_TREADY_int_regslice;
wire    regslice_both_input2_U_ack_in;
wire    regslice_both_input3_U_apdone_blk;
wire   [7:0] input3_TDATA_int_regslice;
wire    input3_TVALID_int_regslice;
reg    input3_TREADY_int_regslice;
wire    regslice_both_input3_U_ack_in;
wire    regslice_both_input4_U_apdone_blk;
wire   [7:0] input4_TDATA_int_regslice;
wire    input4_TVALID_int_regslice;
reg    input4_TREADY_int_regslice;
wire    regslice_both_input4_U_ack_in;
wire    regslice_both_input5_U_apdone_blk;
wire   [7:0] input5_TDATA_int_regslice;
wire    input5_TVALID_int_regslice;
reg    input5_TREADY_int_regslice;
wire    regslice_both_input5_U_ack_in;
wire    regslice_both_input6_U_apdone_blk;
wire   [7:0] input6_TDATA_int_regslice;
wire    input6_TVALID_int_regslice;
reg    input6_TREADY_int_regslice;
wire    regslice_both_input6_U_ack_in;
wire    cp_outre_TVALID_int_regslice;
wire    cp_outre_TREADY_int_regslice;
wire    regslice_both_cp_outre_V_data_V_U_vld_out;
wire    regslice_both_cp_outre_V_keep_V_U_apdone_blk;
wire    regslice_both_cp_outre_V_keep_V_U_ack_in_dummy;
wire    regslice_both_cp_outre_V_keep_V_U_vld_out;
wire    regslice_both_cp_outre_V_strb_V_U_apdone_blk;
wire    regslice_both_cp_outre_V_strb_V_U_ack_in_dummy;
wire    regslice_both_cp_outre_V_strb_V_U_vld_out;
wire    regslice_both_cp_outre_V_last_V_U_apdone_blk;
wire    regslice_both_cp_outre_V_last_V_U_ack_in_dummy;
wire    regslice_both_cp_outre_V_last_V_U_vld_out;
wire    cp_outim_TVALID_int_regslice;
wire    cp_outim_TREADY_int_regslice;
wire    regslice_both_cp_outim_V_data_V_U_vld_out;
wire    regslice_both_cp_outim_V_keep_V_U_apdone_blk;
wire    regslice_both_cp_outim_V_keep_V_U_ack_in_dummy;
wire    regslice_both_cp_outim_V_keep_V_U_vld_out;
wire    regslice_both_cp_outim_V_strb_V_U_apdone_blk;
wire    regslice_both_cp_outim_V_strb_V_U_ack_in_dummy;
wire    regslice_both_cp_outim_V_strb_V_U_vld_out;
wire    regslice_both_cp_outim_V_last_V_U_apdone_blk;
wire    regslice_both_cp_outim_V_last_V_U_ack_in_dummy;
wire    regslice_both_cp_outim_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 grp_mods_fu_261_ap_start_reg = 1'b0;
#0 grp_adding_pilot_fu_293_ap_start_reg = 1'b0;
#0 grp_top_tx_Pipeline_input_loop_fu_309_ap_start_reg = 1'b0;
#0 grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start_reg = 1'b0;
#0 grp_top_tx_Pipeline_loop_output_fu_325_ap_start_reg = 1'b0;
#0 grp_fft_syn_config1_s_fu_347_ap_start_reg = 1'b0;
#0 grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start_reg = 1'b0;
#0 grp_cp_fu_363_ap_start_reg = 1'b0;
end

top_tx_temp2_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 7168 ),
    .AddressWidth( 13 ))
temp2_re_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp2_re_address0),
    .ce0(temp2_re_ce0),
    .we0(temp2_re_we0),
    .d0(grp_adding_pilot_fu_293_out_re_arr_d0),
    .q0(temp2_re_q0)
);

top_tx_temp2_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 7168 ),
    .AddressWidth( 13 ))
temp2_im_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp2_im_address0),
    .ce0(temp2_im_ce0),
    .we0(temp2_im_we0),
    .d0(grp_adding_pilot_fu_293_out_im_arr_d0),
    .q0(temp2_im_q0)
);

top_tx_temp2_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 7168 ),
    .AddressWidth( 13 ))
temp_out_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_out_M_real_address0),
    .ce0(temp_out_M_real_ce0),
    .we0(temp_out_M_real_we0),
    .d0(temp_out_M_real_d0),
    .q0(temp_out_M_real_q0)
);

top_tx_temp2_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 7168 ),
    .AddressWidth( 13 ))
temp_out_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_out_M_imag_address0),
    .ce0(temp_out_M_imag_ce0),
    .we0(temp_out_M_imag_we0),
    .d0(temp_out_M_imag_d0),
    .q0(temp_out_M_imag_q0)
);

top_tx_temp_out1_M_real_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8176 ),
    .AddressWidth( 13 ))
temp_out1_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_out1_M_real_address0),
    .ce0(temp_out1_M_real_ce0),
    .we0(temp_out1_M_real_we0),
    .d0(grp_cp_fu_363_cp_out_M_real_d0),
    .q0(temp_out1_M_real_q0)
);

top_tx_temp_out1_M_real_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8176 ),
    .AddressWidth( 13 ))
temp_out1_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_out1_M_imag_address0),
    .ce0(temp_out1_M_imag_ce0),
    .we0(temp_out1_M_imag_we0),
    .d0(grp_cp_fu_363_cp_out_M_imag_d0),
    .q0(temp_out1_M_imag_q0)
);

top_tx_mods grp_mods_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mods_fu_261_ap_start),
    .ap_done(grp_mods_fu_261_ap_done),
    .ap_idle(grp_mods_fu_261_ap_idle),
    .ap_ready(grp_mods_fu_261_ap_ready),
    .en_qpsk(en_qpsk),
    .en_qam16(en_qam16),
    .en_qam64(en_qam64),
    .input1_TDATA(input1_TDATA_int_regslice),
    .input1_TVALID(input1_TVALID_int_regslice),
    .input1_TREADY(grp_mods_fu_261_input1_TREADY),
    .input2_TDATA(input2_TDATA_int_regslice),
    .input2_TVALID(input2_TVALID_int_regslice),
    .input2_TREADY(grp_mods_fu_261_input2_TREADY),
    .input3_TDATA(input3_TDATA_int_regslice),
    .input3_TVALID(input3_TVALID_int_regslice),
    .input3_TREADY(grp_mods_fu_261_input3_TREADY),
    .input4_TDATA(input4_TDATA_int_regslice),
    .input4_TVALID(input4_TVALID_int_regslice),
    .input4_TREADY(grp_mods_fu_261_input4_TREADY),
    .input5_TDATA(input5_TDATA_int_regslice),
    .input5_TVALID(input5_TVALID_int_regslice),
    .input5_TREADY(grp_mods_fu_261_input5_TREADY),
    .input6_TDATA(input6_TDATA_int_regslice),
    .input6_TVALID(input6_TVALID_int_regslice),
    .input6_TREADY(grp_mods_fu_261_input6_TREADY),
    .temp1_re_din(grp_mods_fu_261_temp1_re_din),
    .temp1_re_full_n(temp1_re_full_n),
    .temp1_re_write(grp_mods_fu_261_temp1_re_write),
    .temp1_im_din(grp_mods_fu_261_temp1_im_din),
    .temp1_im_full_n(temp1_im_full_n),
    .temp1_im_write(grp_mods_fu_261_temp1_im_write)
);

top_tx_adding_pilot grp_adding_pilot_fu_293(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_adding_pilot_fu_293_ap_start),
    .ap_done(grp_adding_pilot_fu_293_ap_done),
    .ap_idle(grp_adding_pilot_fu_293_ap_idle),
    .ap_ready(grp_adding_pilot_fu_293_ap_ready),
    .user_id0(user_id0),
    .user_id1(user_id1),
    .temp1_re_dout(temp1_re_dout),
    .temp1_re_empty_n(temp1_re_empty_n),
    .temp1_re_read(grp_adding_pilot_fu_293_temp1_re_read),
    .temp1_im_dout(temp1_im_dout),
    .temp1_im_empty_n(temp1_im_empty_n),
    .temp1_im_read(grp_adding_pilot_fu_293_temp1_im_read),
    .out_re_arr_address0(grp_adding_pilot_fu_293_out_re_arr_address0),
    .out_re_arr_ce0(grp_adding_pilot_fu_293_out_re_arr_ce0),
    .out_re_arr_we0(grp_adding_pilot_fu_293_out_re_arr_we0),
    .out_re_arr_d0(grp_adding_pilot_fu_293_out_re_arr_d0),
    .out_im_arr_address0(grp_adding_pilot_fu_293_out_im_arr_address0),
    .out_im_arr_ce0(grp_adding_pilot_fu_293_out_im_arr_ce0),
    .out_im_arr_we0(grp_adding_pilot_fu_293_out_im_arr_we0),
    .out_im_arr_d0(grp_adding_pilot_fu_293_out_im_arr_d0)
);

top_tx_top_tx_Pipeline_input_loop grp_top_tx_Pipeline_input_loop_fu_309(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_tx_Pipeline_input_loop_fu_309_ap_start),
    .ap_done(grp_top_tx_Pipeline_input_loop_fu_309_ap_done),
    .ap_idle(grp_top_tx_Pipeline_input_loop_fu_309_ap_idle),
    .ap_ready(grp_top_tx_Pipeline_input_loop_fu_309_ap_ready),
    .temp2_re_address0(grp_top_tx_Pipeline_input_loop_fu_309_temp2_re_address0),
    .temp2_re_ce0(grp_top_tx_Pipeline_input_loop_fu_309_temp2_re_ce0),
    .temp2_re_q0(temp2_re_q0),
    .temp2_im_address0(grp_top_tx_Pipeline_input_loop_fu_309_temp2_im_address0),
    .temp2_im_ce0(grp_top_tx_Pipeline_input_loop_fu_309_temp2_im_ce0),
    .temp2_im_q0(temp2_im_q0),
    .temp_out_M_real_address0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_address0),
    .temp_out_M_real_ce0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_ce0),
    .temp_out_M_real_we0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_we0),
    .temp_out_M_real_d0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_d0),
    .temp_out_M_imag_address0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_address0),
    .temp_out_M_imag_ce0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_ce0),
    .temp_out_M_imag_we0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_we0),
    .temp_out_M_imag_d0(grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_d0)
);

top_tx_top_tx_Pipeline_VITIS_LOOP_14_1 grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start),
    .ap_done(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_done),
    .ap_idle(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_idle),
    .ap_ready(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_ready),
    .xn_i_din(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_xn_i_din),
    .xn_i_full_n(xn_i_full_n),
    .xn_i_write(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_xn_i_write),
    .zext_ln15(tmp_3_reg_509),
    .temp_out_M_real_address0(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_real_address0),
    .temp_out_M_real_ce0(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_real_ce0),
    .temp_out_M_real_q0(temp_out_M_real_q0),
    .temp_out_M_imag_address0(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_imag_address0),
    .temp_out_M_imag_ce0(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_imag_ce0),
    .temp_out_M_imag_q0(temp_out_M_imag_q0)
);

top_tx_top_tx_Pipeline_loop_output grp_top_tx_Pipeline_loop_output_fu_325(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_tx_Pipeline_loop_output_fu_325_ap_start),
    .ap_done(grp_top_tx_Pipeline_loop_output_fu_325_ap_done),
    .ap_idle(grp_top_tx_Pipeline_loop_output_fu_325_ap_idle),
    .ap_ready(grp_top_tx_Pipeline_loop_output_fu_325_ap_ready),
    .cp_outre_TREADY(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TREADY),
    .cp_outim_TREADY(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TREADY),
    .temp_out1_M_real_address0(grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_real_address0),
    .temp_out1_M_real_ce0(grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_real_ce0),
    .temp_out1_M_real_q0(temp_out1_M_real_q0),
    .temp_out1_M_imag_address0(grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_imag_address0),
    .temp_out1_M_imag_ce0(grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_imag_ce0),
    .temp_out1_M_imag_q0(temp_out1_M_imag_q0),
    .cp_outre_TDATA(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TDATA),
    .cp_outre_TVALID(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID),
    .cp_outre_TKEEP(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TKEEP),
    .cp_outre_TSTRB(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TSTRB),
    .cp_outre_TLAST(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TLAST),
    .cp_outim_TDATA(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TDATA),
    .cp_outim_TVALID(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID),
    .cp_outim_TKEEP(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TKEEP),
    .cp_outim_TSTRB(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TSTRB),
    .cp_outim_TLAST(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TLAST)
);

top_tx_fft_syn_config1_s grp_fft_syn_config1_s_fu_347(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_ce(grp_fft_syn_config1_s_fu_347_ap_ce),
    .ap_start(grp_fft_syn_config1_s_fu_347_ap_start),
    .ap_done(grp_fft_syn_config1_s_fu_347_ap_done),
    .ap_idle(grp_fft_syn_config1_s_fu_347_ap_idle),
    .ap_ready(grp_fft_syn_config1_s_fu_347_ap_ready),
    .xn_dout(xn_i_dout),
    .xn_empty_n(xn_i_empty_n),
    .xn_read(grp_fft_syn_config1_s_fu_347_xn_read),
    .xk_din(grp_fft_syn_config1_s_fu_347_xk_din),
    .xk_full_n(xk_i_full_n),
    .xk_write(grp_fft_syn_config1_s_fu_347_xk_write),
    .status_data_V_din(grp_fft_syn_config1_s_fu_347_status_data_V_din),
    .status_data_V_full_n(status_s_full_n),
    .status_data_V_write(grp_fft_syn_config1_s_fu_347_status_data_V_write),
    .config_ch_data_V_dout(config_s_dout),
    .config_ch_data_V_empty_n(config_s_empty_n),
    .config_ch_data_V_read(grp_fft_syn_config1_s_fu_347_config_ch_data_V_read)
);

top_tx_top_tx_Pipeline_VITIS_LOOP_26_1 grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start),
    .ap_done(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_done),
    .ap_idle(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_idle),
    .ap_ready(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_ready),
    .xk_i_dout(xk_i_dout),
    .xk_i_empty_n(xk_i_empty_n),
    .xk_i_read(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_xk_i_read),
    .zext_ln15(tmp_3_reg_509),
    .temp_out_M_real_address0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_address0),
    .temp_out_M_real_ce0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_ce0),
    .temp_out_M_real_we0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_we0),
    .temp_out_M_real_d0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_d0),
    .temp_out_M_imag_address0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_address0),
    .temp_out_M_imag_ce0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_ce0),
    .temp_out_M_imag_we0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_we0),
    .temp_out_M_imag_d0(grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_d0)
);

top_tx_cp grp_cp_fu_363(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cp_fu_363_ap_start),
    .ap_done(grp_cp_fu_363_ap_done),
    .ap_idle(grp_cp_fu_363_ap_idle),
    .ap_ready(grp_cp_fu_363_ap_ready),
    .nocp_M_real_address0(grp_cp_fu_363_nocp_M_real_address0),
    .nocp_M_real_ce0(grp_cp_fu_363_nocp_M_real_ce0),
    .nocp_M_real_q0(temp_out_M_real_q0),
    .nocp_M_real_offset(block_1_reg_501),
    .nocp_M_imag_address0(grp_cp_fu_363_nocp_M_imag_address0),
    .nocp_M_imag_ce0(grp_cp_fu_363_nocp_M_imag_ce0),
    .nocp_M_imag_q0(temp_out_M_imag_q0),
    .cp_out_M_real_address0(grp_cp_fu_363_cp_out_M_real_address0),
    .cp_out_M_real_ce0(grp_cp_fu_363_cp_out_M_real_ce0),
    .cp_out_M_real_we0(grp_cp_fu_363_cp_out_M_real_we0),
    .cp_out_M_real_d0(grp_cp_fu_363_cp_out_M_real_d0),
    .cp_out_M_imag_address0(grp_cp_fu_363_cp_out_M_imag_address0),
    .cp_out_M_imag_ce0(grp_cp_fu_363_cp_out_M_imag_ce0),
    .cp_out_M_imag_we0(grp_cp_fu_363_cp_out_M_imag_we0),
    .cp_out_M_imag_d0(grp_cp_fu_363_cp_out_M_imag_d0)
);

top_tx_fifo_w16_d2_S config_s_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(config_s_din),
    .if_full_n(config_s_full_n),
    .if_write(config_s_write),
    .if_dout(config_s_dout),
    .if_empty_n(config_s_empty_n),
    .if_read(config_s_read)
);

top_tx_fifo_w8_d2_S status_s_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_syn_config1_s_fu_347_status_data_V_din),
    .if_full_n(status_s_full_n),
    .if_write(status_s_write),
    .if_dout(status_s_dout),
    .if_empty_n(status_s_empty_n),
    .if_read(status_s_read)
);

top_tx_fifo_w32_d1024_A xn_i_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_xn_i_din),
    .if_full_n(xn_i_full_n),
    .if_write(xn_i_write),
    .if_dout(xn_i_dout),
    .if_empty_n(xn_i_empty_n),
    .if_read(xn_i_read)
);

top_tx_fifo_w32_d1024_A xk_i_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_syn_config1_s_fu_347_xk_din),
    .if_full_n(xk_i_full_n),
    .if_write(xk_i_write),
    .if_dout(xk_i_dout),
    .if_empty_n(xk_i_empty_n),
    .if_read(xk_i_read)
);

top_tx_fifo_w16_d3600_A temp1_re_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_mods_fu_261_temp1_re_din),
    .if_full_n(temp1_re_full_n),
    .if_write(temp1_re_write),
    .if_dout(temp1_re_dout),
    .if_empty_n(temp1_re_empty_n),
    .if_read(temp1_re_read)
);

top_tx_fifo_w16_d3600_A temp1_im_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_mods_fu_261_temp1_im_din),
    .if_full_n(temp1_im_full_n),
    .if_write(temp1_im_write),
    .if_dout(temp1_im_dout),
    .if_empty_n(temp1_im_empty_n),
    .if_read(temp1_im_read)
);

top_tx_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input1_TDATA),
    .vld_in(input1_TVALID),
    .ack_in(regslice_both_input1_U_ack_in),
    .data_out(input1_TDATA_int_regslice),
    .vld_out(input1_TVALID_int_regslice),
    .ack_out(input1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input1_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input2_TDATA),
    .vld_in(input2_TVALID),
    .ack_in(regslice_both_input2_U_ack_in),
    .data_out(input2_TDATA_int_regslice),
    .vld_out(input2_TVALID_int_regslice),
    .ack_out(input2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input2_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input3_TDATA),
    .vld_in(input3_TVALID),
    .ack_in(regslice_both_input3_U_ack_in),
    .data_out(input3_TDATA_int_regslice),
    .vld_out(input3_TVALID_int_regslice),
    .ack_out(input3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input3_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input4_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input4_TDATA),
    .vld_in(input4_TVALID),
    .ack_in(regslice_both_input4_U_ack_in),
    .data_out(input4_TDATA_int_regslice),
    .vld_out(input4_TVALID_int_regslice),
    .ack_out(input4_TREADY_int_regslice),
    .apdone_blk(regslice_both_input4_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input5_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input5_TDATA),
    .vld_in(input5_TVALID),
    .ack_in(regslice_both_input5_U_ack_in),
    .data_out(input5_TDATA_int_regslice),
    .vld_out(input5_TVALID_int_regslice),
    .ack_out(input5_TREADY_int_regslice),
    .apdone_blk(regslice_both_input5_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input6_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input6_TDATA),
    .vld_in(input6_TVALID),
    .ack_in(regslice_both_input6_U_ack_in),
    .data_out(input6_TDATA_int_regslice),
    .vld_out(input6_TVALID_int_regslice),
    .ack_out(input6_TREADY_int_regslice),
    .apdone_blk(regslice_both_input6_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 16 ))
regslice_both_cp_outre_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TDATA),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID),
    .ack_in(cp_outre_TREADY_int_regslice),
    .data_out(cp_outre_TDATA),
    .vld_out(regslice_both_cp_outre_V_data_V_U_vld_out),
    .ack_out(cp_outre_TREADY),
    .apdone_blk(regslice_both_cp_outre_V_data_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 2 ))
regslice_both_cp_outre_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TKEEP),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID),
    .ack_in(regslice_both_cp_outre_V_keep_V_U_ack_in_dummy),
    .data_out(cp_outre_TKEEP),
    .vld_out(regslice_both_cp_outre_V_keep_V_U_vld_out),
    .ack_out(cp_outre_TREADY),
    .apdone_blk(regslice_both_cp_outre_V_keep_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 2 ))
regslice_both_cp_outre_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TSTRB),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID),
    .ack_in(regslice_both_cp_outre_V_strb_V_U_ack_in_dummy),
    .data_out(cp_outre_TSTRB),
    .vld_out(regslice_both_cp_outre_V_strb_V_U_vld_out),
    .ack_out(cp_outre_TREADY),
    .apdone_blk(regslice_both_cp_outre_V_strb_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 1 ))
regslice_both_cp_outre_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TLAST),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID),
    .ack_in(regslice_both_cp_outre_V_last_V_U_ack_in_dummy),
    .data_out(cp_outre_TLAST),
    .vld_out(regslice_both_cp_outre_V_last_V_U_vld_out),
    .ack_out(cp_outre_TREADY),
    .apdone_blk(regslice_both_cp_outre_V_last_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 16 ))
regslice_both_cp_outim_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TDATA),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID),
    .ack_in(cp_outim_TREADY_int_regslice),
    .data_out(cp_outim_TDATA),
    .vld_out(regslice_both_cp_outim_V_data_V_U_vld_out),
    .ack_out(cp_outim_TREADY),
    .apdone_blk(regslice_both_cp_outim_V_data_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 2 ))
regslice_both_cp_outim_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TKEEP),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID),
    .ack_in(regslice_both_cp_outim_V_keep_V_U_ack_in_dummy),
    .data_out(cp_outim_TKEEP),
    .vld_out(regslice_both_cp_outim_V_keep_V_U_vld_out),
    .ack_out(cp_outim_TREADY),
    .apdone_blk(regslice_both_cp_outim_V_keep_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 2 ))
regslice_both_cp_outim_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TSTRB),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID),
    .ack_in(regslice_both_cp_outim_V_strb_V_U_ack_in_dummy),
    .data_out(cp_outim_TSTRB),
    .vld_out(regslice_both_cp_outim_V_strb_V_U_vld_out),
    .ack_out(cp_outim_TREADY),
    .apdone_blk(regslice_both_cp_outim_V_strb_V_U_apdone_blk)
);

top_tx_regslice_both #(
    .DataWidth( 1 ))
regslice_both_cp_outim_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TLAST),
    .vld_in(grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID),
    .ack_in(regslice_both_cp_outim_V_last_V_U_ack_in_dummy),
    .data_out(cp_outim_TLAST),
    .vld_out(regslice_both_cp_outim_V_last_V_U_vld_out),
    .ack_out(cp_outim_TREADY),
    .apdone_blk(regslice_both_cp_outim_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_adding_pilot_fu_293_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_adding_pilot_fu_293_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_fu_293_ap_ready == 1'b1)) begin
            grp_adding_pilot_fu_293_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cp_fu_363_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_cp_fu_363_ap_start_reg <= 1'b1;
        end else if ((grp_cp_fu_363_ap_ready == 1'b1)) begin
            grp_cp_fu_363_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fft_syn_config1_s_fu_347_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_fft_syn_config1_s_fu_347_ap_start_reg <= 1'b1;
        end else if ((grp_fft_syn_config1_s_fu_347_ap_ready == 1'b1)) begin
            grp_fft_syn_config1_s_fu_347_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mods_fu_261_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_mods_fu_261_ap_start_reg <= 1'b1;
        end else if ((grp_mods_fu_261_ap_ready == 1'b1)) begin
            grp_mods_fu_261_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln109_fu_380_p2 == 1'd0))) begin
            grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start_reg <= 1'b1;
        end else if ((grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_ready == 1'b1)) begin
            grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start_reg <= 1'b1;
        end else if ((grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_ready == 1'b1)) begin
            grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_tx_Pipeline_input_loop_fu_309_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_top_tx_Pipeline_input_loop_fu_309_ap_start_reg <= 1'b1;
        end else if ((grp_top_tx_Pipeline_input_loop_fu_309_ap_ready == 1'b1)) begin
            grp_top_tx_Pipeline_input_loop_fu_309_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_tx_Pipeline_loop_output_fu_325_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln109_fu_380_p2 == 1'd1))) begin
            grp_top_tx_Pipeline_loop_output_fu_325_ap_start_reg <= 1'b1;
        end else if ((grp_top_tx_Pipeline_loop_output_fu_325_ap_ready == 1'b1)) begin
            grp_top_tx_Pipeline_loop_output_fu_325_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        block_fu_168 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln109_fu_380_p2 == 1'd0))) begin
        block_fu_168 <= add_ln109_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        block_1_reg_501 <= block_fu_168;
    end
end

always @ (posedge ap_clk) begin
    if (((config_s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        fft_config_fu_164 <= fft_config_1_fu_409_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln109_fu_380_p2 == 1'd0))) begin
        tmp_3_reg_509[12 : 10] <= tmp_3_fu_392_p3[12 : 10];
    end
end

always @ (*) begin
    if ((config_s_full_n == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_syn_config1_s_fu_347_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((status_s_empty_n == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_cp_fu_363_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_top_tx_Pipeline_loop_output_fu_325_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_cp_outim_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_cp_outre_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mods_fu_261_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_adding_pilot_fu_293_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_top_tx_Pipeline_input_loop_fu_309_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_cp_outim_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_cp_outre_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_cp_outim_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_cp_outre_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        config_s_read = grp_fft_syn_config1_s_fu_347_config_ch_data_V_read;
    end else begin
        config_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((config_s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        config_s_write = 1'b1;
    end else begin
        config_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        grp_fft_syn_config1_s_fu_347_ap_ce = 1'b1;
    end else begin
        grp_fft_syn_config1_s_fu_347_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input1_TREADY_int_regslice = grp_mods_fu_261_input1_TREADY;
    end else begin
        input1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input2_TREADY_int_regslice = grp_mods_fu_261_input2_TREADY;
    end else begin
        input2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input3_TREADY_int_regslice = grp_mods_fu_261_input3_TREADY;
    end else begin
        input3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input4_TREADY_int_regslice = grp_mods_fu_261_input4_TREADY;
    end else begin
        input4_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input5_TREADY_int_regslice = grp_mods_fu_261_input5_TREADY;
    end else begin
        input5_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input6_TREADY_int_regslice = grp_mods_fu_261_input6_TREADY;
    end else begin
        input6_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((status_s_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        status_s_read = 1'b1;
    end else begin
        status_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        status_s_write = grp_fft_syn_config1_s_fu_347_status_data_V_write;
    end else begin
        status_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        temp1_im_read = grp_adding_pilot_fu_293_temp1_im_read;
    end else begin
        temp1_im_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp1_im_write = grp_mods_fu_261_temp1_im_write;
    end else begin
        temp1_im_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        temp1_re_read = grp_adding_pilot_fu_293_temp1_re_read;
    end else begin
        temp1_re_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp1_re_write = grp_mods_fu_261_temp1_re_write;
    end else begin
        temp1_re_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp2_im_address0 = grp_top_tx_Pipeline_input_loop_fu_309_temp2_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp2_im_address0 = grp_adding_pilot_fu_293_out_im_arr_address0;
    end else begin
        temp2_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp2_im_ce0 = grp_top_tx_Pipeline_input_loop_fu_309_temp2_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp2_im_ce0 = grp_adding_pilot_fu_293_out_im_arr_ce0;
    end else begin
        temp2_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        temp2_im_we0 = grp_adding_pilot_fu_293_out_im_arr_we0;
    end else begin
        temp2_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp2_re_address0 = grp_top_tx_Pipeline_input_loop_fu_309_temp2_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp2_re_address0 = grp_adding_pilot_fu_293_out_re_arr_address0;
    end else begin
        temp2_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp2_re_ce0 = grp_top_tx_Pipeline_input_loop_fu_309_temp2_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp2_re_ce0 = grp_adding_pilot_fu_293_out_re_arr_ce0;
    end else begin
        temp2_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        temp2_re_we0 = grp_adding_pilot_fu_293_out_re_arr_we0;
    end else begin
        temp2_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out1_M_imag_address0 = grp_cp_fu_363_cp_out_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_out1_M_imag_address0 = grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_imag_address0;
    end else begin
        temp_out1_M_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out1_M_imag_ce0 = grp_cp_fu_363_cp_out_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_out1_M_imag_ce0 = grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_imag_ce0;
    end else begin
        temp_out1_M_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out1_M_imag_we0 = grp_cp_fu_363_cp_out_M_imag_we0;
    end else begin
        temp_out1_M_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out1_M_real_address0 = grp_cp_fu_363_cp_out_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_out1_M_real_address0 = grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_real_address0;
    end else begin
        temp_out1_M_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out1_M_real_ce0 = grp_cp_fu_363_cp_out_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_out1_M_real_ce0 = grp_top_tx_Pipeline_loop_output_fu_325_temp_out1_M_real_ce0;
    end else begin
        temp_out1_M_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out1_M_real_we0 = grp_cp_fu_363_cp_out_M_real_we0;
    end else begin
        temp_out1_M_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out_M_imag_address0 = grp_cp_fu_363_nocp_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_imag_address0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_out_M_imag_address0 = grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_imag_address0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_address0;
    end else begin
        temp_out_M_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out_M_imag_ce0 = grp_cp_fu_363_nocp_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_imag_ce0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_out_M_imag_ce0 = grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_imag_ce0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_ce0;
    end else begin
        temp_out_M_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_imag_d0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_imag_d0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_d0;
    end else begin
        temp_out_M_imag_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_imag_we0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_imag_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_imag_we0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_imag_we0;
    end else begin
        temp_out_M_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out_M_real_address0 = grp_cp_fu_363_nocp_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_real_address0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_out_M_real_address0 = grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_real_address0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_address0;
    end else begin
        temp_out_M_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_out_M_real_ce0 = grp_cp_fu_363_nocp_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_real_ce0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_out_M_real_ce0 = grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_temp_out_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_real_ce0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_ce0;
    end else begin
        temp_out_M_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_real_d0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_real_d0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_d0;
    end else begin
        temp_out_M_real_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        temp_out_M_real_we0 = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_temp_out_M_real_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_out_M_real_we0 = grp_top_tx_Pipeline_input_loop_fu_309_temp_out_M_real_we0;
    end else begin
        temp_out_M_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        xk_i_read = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_xk_i_read;
    end else begin
        xk_i_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        xk_i_write = grp_fft_syn_config1_s_fu_347_xk_write;
    end else begin
        xk_i_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        xn_i_read = grp_fft_syn_config1_s_fu_347_xn_read;
    end else begin
        xn_i_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        xn_i_write = grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_xn_i_write;
    end else begin
        xn_i_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_mods_fu_261_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_adding_pilot_fu_293_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_top_tx_Pipeline_input_loop_fu_309_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln109_fu_380_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((config_s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_fft_syn_config1_s_fu_347_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((status_s_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_cp_fu_363_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((grp_top_tx_Pipeline_loop_output_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if ((~((regslice_both_cp_outim_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_cp_outre_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_386_p2 = (block_fu_168 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state19 = ((regslice_both_cp_outim_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_cp_outre_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign config_s_din = {{fft_config_fu_164[15:11]}, {11'd1366}};

assign cp_outim_TVALID = regslice_both_cp_outim_V_data_V_U_vld_out;

assign cp_outim_TVALID_int_regslice = grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TVALID;

assign cp_outre_TVALID = regslice_both_cp_outre_V_data_V_U_vld_out;

assign cp_outre_TVALID_int_regslice = grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TVALID;

assign fft_config_1_fu_409_p5 = {{fft_config_fu_164[15:11]}, {11'd1366}};

assign grp_adding_pilot_fu_293_ap_start = grp_adding_pilot_fu_293_ap_start_reg;

assign grp_cp_fu_363_ap_start = grp_cp_fu_363_ap_start_reg;

assign grp_fft_syn_config1_s_fu_347_ap_start = grp_fft_syn_config1_s_fu_347_ap_start_reg;

assign grp_mods_fu_261_ap_start = grp_mods_fu_261_ap_start_reg;

assign grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start = grp_top_tx_Pipeline_VITIS_LOOP_14_1_fu_317_ap_start_reg;

assign grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start = grp_top_tx_Pipeline_VITIS_LOOP_26_1_fu_355_ap_start_reg;

assign grp_top_tx_Pipeline_input_loop_fu_309_ap_start = grp_top_tx_Pipeline_input_loop_fu_309_ap_start_reg;

assign grp_top_tx_Pipeline_loop_output_fu_325_ap_start = grp_top_tx_Pipeline_loop_output_fu_325_ap_start_reg;

assign grp_top_tx_Pipeline_loop_output_fu_325_cp_outim_TREADY = (cp_outim_TREADY_int_regslice & ap_CS_fsm_state18);

assign grp_top_tx_Pipeline_loop_output_fu_325_cp_outre_TREADY = (cp_outre_TREADY_int_regslice & ap_CS_fsm_state18);

assign icmp_ln109_fu_380_p2 = ((block_fu_168 == 3'd7) ? 1'b1 : 1'b0);

assign input1_TREADY = regslice_both_input1_U_ack_in;

assign input2_TREADY = regslice_both_input2_U_ack_in;

assign input3_TREADY = regslice_both_input3_U_ack_in;

assign input4_TREADY = regslice_both_input4_U_ack_in;

assign input5_TREADY = regslice_both_input5_U_ack_in;

assign input6_TREADY = regslice_both_input6_U_ack_in;

assign tmp_3_fu_392_p3 = {{block_fu_168}, {10'd0}};

always @ (posedge ap_clk) begin
    tmp_3_reg_509[9:0] <= 10'b0000000000;
end

endmodule //top_tx
