// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_tx_qpsk (
        input1_val,
        input2_val,
        temp1_re_din,
        temp1_re_full_n,
        temp1_re_write,
        temp1_im_din,
        temp1_im_full_n,
        temp1_im_write,
        ap_clk,
        ap_rst,
        input2_val_ap_vld,
        input1_val_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [0:0] input1_val;
input  [0:0] input2_val;
output  [15:0] temp1_re_din;
input   temp1_re_full_n;
output   temp1_re_write;
output  [15:0] temp1_im_din;
input   temp1_im_full_n;
output   temp1_im_write;
input   ap_clk;
input   ap_rst;
input   input2_val_ap_vld;
input   input1_val_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    qpsk_Block_entry11_proc26_U0_ap_start;
wire    qpsk_Block_entry11_proc26_U0_ap_done;
wire    qpsk_Block_entry11_proc26_U0_ap_continue;
wire    qpsk_Block_entry11_proc26_U0_ap_idle;
wire    qpsk_Block_entry11_proc26_U0_ap_ready;
wire   [15:0] qpsk_Block_entry11_proc26_U0_temp1_re_din;
wire    qpsk_Block_entry11_proc26_U0_temp1_re_write;
wire   [15:0] qpsk_Block_entry11_proc26_U0_temp1_im_din;
wire    qpsk_Block_entry11_proc26_U0_temp1_im_write;

top_tx_qpsk_Block_entry11_proc26 qpsk_Block_entry11_proc26_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(qpsk_Block_entry11_proc26_U0_ap_start),
    .ap_done(qpsk_Block_entry11_proc26_U0_ap_done),
    .ap_continue(qpsk_Block_entry11_proc26_U0_ap_continue),
    .ap_idle(qpsk_Block_entry11_proc26_U0_ap_idle),
    .ap_ready(qpsk_Block_entry11_proc26_U0_ap_ready),
    .input2_val(input2_val),
    .temp1_re_din(qpsk_Block_entry11_proc26_U0_temp1_re_din),
    .temp1_re_full_n(temp1_re_full_n),
    .temp1_re_write(qpsk_Block_entry11_proc26_U0_temp1_re_write),
    .input1_val(input1_val),
    .temp1_im_din(qpsk_Block_entry11_proc26_U0_temp1_im_din),
    .temp1_im_full_n(temp1_im_full_n),
    .temp1_im_write(qpsk_Block_entry11_proc26_U0_temp1_im_write)
);

assign ap_done = qpsk_Block_entry11_proc26_U0_ap_done;

assign ap_idle = qpsk_Block_entry11_proc26_U0_ap_idle;

assign ap_ready = qpsk_Block_entry11_proc26_U0_ap_ready;

assign qpsk_Block_entry11_proc26_U0_ap_continue = ap_continue;

assign qpsk_Block_entry11_proc26_U0_ap_start = ap_start;

assign temp1_im_din = qpsk_Block_entry11_proc26_U0_temp1_im_din;

assign temp1_im_write = qpsk_Block_entry11_proc26_U0_temp1_im_write;

assign temp1_re_din = qpsk_Block_entry11_proc26_U0_temp1_re_din;

assign temp1_re_write = qpsk_Block_entry11_proc26_U0_temp1_re_write;

endmodule //top_tx_qpsk
